### PR TITLE
feat: Add new tool integration -- Jira

### PR DESCRIPTION
**Pull request by tybalex**
**What does this PR do?**
This PR introduce a new default otto8 tool: Jira. 
This is implemented in nodeJS using Jira's v3 REST API.
In this first pass implementation, what the otto8 agent can do from this PR are:
```
Get All Projects, Get Project, Get All Users, Get User, List Issues, Get Issue, Get Issue Types, Get Priority Schemes, Get Available Priorities, Create Issue, Get All Dashboards, Get Dashboard
```

The most important one here is `Create Issue`, with all the other helper tools, the agent can set description, asignee, reporters, priority, etc.. for the new issue too.

I will add a new oauth app type to the main Otto8 repo in a separate PR.

### CODE REVIEW

**Comment by tybalex** [comment]
Here is an example:
Screenshot 2024-12-12 at 5 08 45 PM

**Comment by tybalex** [comment]
@cjellick please let me know if there's any extra tools you'd like to see.

**Comment by tybalex** [comment]
Oauth configured:
Screenshot 2024-12-14 at 1 41 49 PM

**Comment by njhale** [comment]
This PR has been subsumed by #291. Closing this out.

**Pull request closed without merging**
